# -*- coding: utf-8 -*-
"""2_Facial_Landmark_detection_git.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVUghOnAcHUsyiOMSdQZe_g-G2Sbea42
"""

# Mount drive
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('./drive/My Drive/Facial_detection/')

!pip install face_recognition

!pwd

import PIL.Image
import PIL.ImageDraw
import face_recognition


# Load the jpg file into a numpy array
image = face_recognition.load_image_file("./images.jpeg")


# Find all facial features in all the faces in the image
face_landmarks_list = face_recognition.face_landmarks(image)

number_of_faces = len(face_landmarks_list)
print("I found {} face(s) in this photograph.".format(number_of_faces))

# Load the image into a Python Image Library object so that we can draw on top of it and display it
pil_image = PIL.Image.fromarray(image)

# Create a PIL drawing object to be able to draw lines later
draw = PIL.ImageDraw.Draw(pil_image)

# Loop over each face
for face_landmarks in face_landmarks_list:

    # Loop over each facial feature (eye, nose, mouth, lips, etc)
    for name, list_of_points in face_landmarks.items():

        # Print the location of each facial feature in this image
        print("The {} in this face has the following points: {}".format(name, list_of_points))
        draw.point(list_of_points,fill=(255, 255, 0))

        # Let's trace out each facial feature in the image with a line!
        #draw.line(list_of_points, fill="red", width=2)

#pil_image.show()
pil_image