# -*- coding: utf-8 -*-
"""4_Face_Recognition_System_git.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5NizqFGrbjELdMFA5GojnYSEDMI9Sd3
"""

# Mount drive
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('./drive/My Drive/Facial_detection/')

!pip install face_recognition

!pwd

import face_recognition
from matplotlib import pyplot as plt

# Load the known images
image_of_person_1 = face_recognition.load_image_file("./images/cropped-2.jpg")
image_of_person_2 = face_recognition.load_image_file("./images/cropped-3.jpg")
image_of_person_3 = face_recognition.load_image_file("./images/cropped.jpg")

# Get the face encoding of each person. This can fail if no one is found in the photo.
person_1_face_encoding = face_recognition.face_encodings(image_of_person_1)[0]
person_2_face_encoding = face_recognition.face_encodings(image_of_person_2)[0]
person_3_face_encoding = face_recognition.face_encodings(image_of_person_3)[0]

# Create a list of all known face encodings
known_face_encodings = [
    person_1_face_encoding,
    person_2_face_encoding,
    person_3_face_encoding
]

# Load the image we want to check
unknown_image = face_recognition.load_image_file("./images/cropped-4.jpg")

# Get face encodings for any people in the picture
unknown_face_encodings = face_recognition.face_encodings(unknown_image)

# There might be more than one person in the photo, so we need to loop over each face we found
for unknown_face_encoding in known_face_encodings:

    # Test if this unknown face encoding matches any of the three people we know
    results = face_recognition.compare_faces(known_face_encodings, unknown_face_encoding, tolerance=0.6)


    name = "Not found"

    if results[0]:
        name = "Dalyne"
    elif results[1]:
        name = "Lydia"
    elif results[2]:
        name = "Jeni"

print(f"Found {name} in the photo!")

fig=plt.figure()
ax1=fig.add_subplot(2,1,1)
ax1.imshow(unknown_image)
plt.xticks([]), plt.yticks([])  # to hide tick values on X and Y axis
#plt.show()

fig= plt.figure()
ax2=fig.add_subplot(2,1,2)


if name=="Dalyne":
  ax2.imshow(image_of_person_1)

if name=="Lydia":
  ax2.imshow(image_of_person_2)

if name=="Jeni":
  ax2.imshow(image_of_person_3)
plt.xticks([]), plt.yticks([])